-------------------------------------------------------------------------------------------------------------------
-- OBJETIVO:                  : Logica para reversion del script ORCLQA_DESARCHIVE_AUTEN_V.01.00.00.sql 
---
-- PARÁMETROS DE ENTRADA:	  : N/A 
-- PARÁMETROS DE SALIDA       : N/A
-- OBJETOS QUE LO REFERENCIAN : N/A
-- LIDER TÉCNICO              : Gabriel Duarte
-- FECHA                      : 2021/10/05
-- REALIZADO POR              : INFORMATICA & TECNOLOGIA (GEDV - JAPC)
--	         Este componente fue realizado bajo la metodología de desarrollo de Informática & Tecnología 
--             y se encuentra Protegido por las leyes de derechos de autor.
-- FECHA MODIFICACIÓN:          
-- LIDER MODIFICACIÓN:          
-- REALIZADO POR:               
-- OBJETIVO MODIFICACIÓN:       
----------------------------------------------------------------------------------------------------------------------
ALTER TABLE SCHQA_DESARCHIVE_AUTEN.USUARIO DROP COLUMN NUMERO_IDENTIFICACION;
ALTER TABLE SCHQA_DESARCHIVE_AUTEN.USUARIO DROP COLUMN EMAIL; 
ALTER TABLE SCHQA_DESARCHIVE_AUTEN.USUARIO DROP COLUMN ID_TIPO_IDENTIFICACION;

ALTER TABLE SCHQA_DESARCHIVE_AUTEN.usuario
    ADD CONSTRAINT FK_DTU_USU FOREIGN KEY ( ID_USUARIO )
        REFERENCES SCHQA_DESARCHIVE_AUTEN.DETALLE_USUARIO ( ID_DETALLE_USUARIO );
		
ALTER TABLE SCHQA_DESARCHIVE_AUTEN.DETALLE_USUARIO DROP CONSTRAINT FK_USU_DTU;

DROP INDEX SCHQA_DESARCHIVE_AUTEN.IDX_USU_DTU;
DROP INDEX SCHQA_DESARCHIVE_AUTEN.IDX_CRD_IDUSUARIO;
DROP SEQUENCE SCHQA_DESARCHIVE_AUTEN.SEQ_DETALLE_USUARIO;
DROP TRIGGER SCHQA_DESARCHIVE_AUTEN.TRG_DETALLE_USUARIO;
DROP TABLE SCHQA_DESARCHIVE_AUTEN.TIPO_IDENTIFICACION;
DROP SEQUENCE SCHQA_DESARCHIVE_AUTEN.SEQ_TIPO_IDENTIFICACION;

