/*
-------------------------------------------------------------------------------------------------------------------------------
-- OBJETIVO                  : SCRIPT DE INSERCION DE LAS TABLAS DEL MODELO
                               
-- PARÁMETROS DE ENTRADA     : N/A
-- PARÁMETROS DE SALIDA      : NA   
-- OBJETOS QUE LO REFERENCIAN: NA
-- LIDER TÉCNICO             :              
-- FECHAHORA                 : 2022/02/18
-- REALIZADO POR             : INFORMATICA & TECNOLOGIA (GEDV - JAPC)
--	                           ESTE COMPONENTE FUE REALIZADO BAJO LA METODOLOGÍA DE DESARROLLO DE INFORMÁTICA & TECNOLOGÍA 
--                             Y SE ENCUENTRA PROTEGIDO POR LAS LEYES DE DERECHOS DE AUTOR.
-- FECHAHORA MODIFICACIÓN    : 
-- LIDER MODIFICACIÓN        : 
-- REALIZADO POR             : JUAN MANUEL NUÑEZ BONILLA
-- OBJETIVO MODIFICACIÓN     : 
-----------------------------------------------------------------------------------------------------------------------------
*/

INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','1','1',TO_DATE('01/01/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','1','11',TO_DATE('11/01/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','3','22',TO_DATE('22/03/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','4','1',TO_DATE('01/04/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','4','2',TO_DATE('02/04/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','5','1',TO_DATE('01/05/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','5','17',TO_DATE('17/05/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','6','3',TO_DATE('03/06/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','6','14',TO_DATE('14/06/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','7','5',TO_DATE('05/07/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','7','20',TO_DATE('20/07/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','8','7',TO_DATE('07/08/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','8','16',TO_DATE('16/08/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','10','18',TO_DATE('18/10/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','11','1',TO_DATE('01/11/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','11','15',TO_DATE('15/11/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','12','8',TO_DATE('08/12/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2021','12','25',TO_DATE('25/12/21','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','1','1',TO_DATE('01/01/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','1','10',TO_DATE('10/01/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','3','21',TO_DATE('21/03/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','4','14',TO_DATE('14/04/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','4','15',TO_DATE('15/04/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','5','1',TO_DATE('01/05/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','5','30',TO_DATE('30/05/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','6','20',TO_DATE('20/06/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','6','27',TO_DATE('27/06/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','7','4',TO_DATE('04/07/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','7','20',TO_DATE('20/07/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','8','7',TO_DATE('07/08/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','8','15',TO_DATE('15/08/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','10','17',TO_DATE('17/10/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','11','7',TO_DATE('07/11/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','11','14',TO_DATE('14/11/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','12','8',TO_DATE('08/12/22','DD/MM/RR'));
INSERT INTO SCH_ORCLQA_DIA_FESTIVO.DIA_FESTIVO (ANIO,MES,DIA,FECHA) VALUES ('2022','12','25',TO_DATE('25/12/22','DD/MM/RR'));
COMMIT;