-------------------------------------------------------------------------------------------------------------------
-- OBJETIVO:                   - Ajustar la tabla USUARIO agregando los campos:
--                               NUMERO_IDENTIFICACION 
--                               EMAIL
--                               ID_TIPO_IDENTIFICACION
--                             - Se crea la tabla TIPO_IDENTIFICACION
--                             - Se crea la relacion entre la tabla TIPO_IDENTIFICACION y USUARIO.
--                             - Se elimina la llave foranea FK_DTU_USU para ajustar la relacion con la tabla DETALLE_USUARIO
--                             - Se crea la llave foranea FK_USU_DTU para ajustar la relacion con la tabla DETALLE_USUARIO
--                             - Se crea la secuencia y trigger de la tabla DETALLE_USUARIO
--                             - Se crea el indice IDX_CRD_IDUSUARIO asociado al campo ID_USUARIO para la tabla CREDENCIAL 
--                               para garantizar la union uno a uno
---
-- PARÁMETROS DE ENTRADA:	  : N/A 
-- PARÁMETROS DE SALIDA       : N/A
-- OBJETOS QUE LO REFERENCIAN : N/A
-- LIDER TÉCNICO              : Gabriel Duarte
-- FECHA                      : 2021/09/29
-- REALIZADO POR              : INFORMATICA & TECNOLOGIA (GEDV - JAPC)
--	         Este componente fue realizado bajo la metodología de desarrollo de Informática & Tecnología 
--             y se encuentra Protegido por las leyes de derechos de autor.
-- FECHA MODIFICACIÓN:          
-- LIDER MODIFICACIÓN:          
-- REALIZADO POR:               
-- OBJETIVO MODIFICACIÓN:       
----------------------------------------------------------------------------------------------------------------------
ALTER TABLE SCHQA_ORCL_DESARCHIVE_AUTEN.USUARIO ADD NUMERO_IDENTIFICACION NVARCHAR2(1000)NOT NULL;
ALTER TABLE SCHQA_ORCL_DESARCHIVE_AUTEN.USUARIO ADD EMAIL NVARCHAR2(1000)NOT NULL;
ALTER TABLE SCHQA_ORCL_DESARCHIVE_AUTEN.USUARIO ADD ID_TIPO_IDENTIFICACION NUMBER(19)NOT NULL;


CREATE TABLE SCHQA_ORCL_DESARCHIVE_AUTEN.TIPO_IDENTIFICACION (
    ID_TIPO_IDENTIFICACION NUMBER(1) NOT NULL,
    NOMBRE                 NVARCHAR2(500)NOT NULL,
    ES_ACTIVO              NUMBER(1)NOT NULL
);
/
ALTER TABLE SCHQA_ORCL_DESARCHIVE_AUTEN.TIPO_IDENTIFICACION ADD CONSTRAINT PK_TID PRIMARY KEY ( ID_TIPO_IDENTIFICACION );

CREATE SEQUENCE SCHQA_ORCL_DESARCHIVE_AUTEN.SEQ_TIPO_IDENTIFICACION START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER SCHQA_ORCL_DESARCHIVE_AUTEN.TRG_TIPO_IDENTIFICACION BEFORE
    INSERT ON SCHQA_ORCL_DESARCHIVE_AUTEN.TIPO_IDENTIFICACION
    FOR EACH ROW
    WHEN ( NEW.ID_TIPO_IDENTIFICACION IS NULL )
BEGIN
    :NEW.ID_TIPO_IDENTIFICACION := SEQ_TIPO_IDENTIFICACION.NEXTVAL;
END;
/

ALTER TABLE SCHQA_ORCL_DESARCHIVE_AUTEN.USUARIO
    ADD CONSTRAINT FK_TID_USU FOREIGN KEY ( ID_TIPO_IDENTIFICACION )
        REFERENCES SCHQA_ORCL_DESARCHIVE_AUTEN.TIPO_IDENTIFICACION ( ID_TIPO_IDENTIFICACION );
		
ALTER TABLE SCHQA_ORCL_DESARCHIVE_AUTEN.USUARIO DROP CONSTRAINT FK_DTU_USU;
ALTER TABLE SCHQA_ORCL_DESARCHIVE_AUTEN.DETALLE_USUARIO ADD CONSTRAINT FK_USU_DTU FOREIGN KEY ( ID_USUARIO ) REFERENCES USUARIO ( ID_USUARIO );
CREATE UNIQUE INDEX SCHQA_ORCL_DESARCHIVE_AUTEN.IDX_USU_DTU ON SCHQA_ORCL_DESARCHIVE_AUTEN.DETALLE_USUARIO (ID_USUARIO ASC );

CREATE UNIQUE INDEX SCHQA_ORCL_DESARCHIVE_AUTEN.IDX_CRD_IDUSUARIO ON SCHQA_ORCL_DESARCHIVE_AUTEN.CREDENCIAL (ID_USUARIO ASC );

CREATE SEQUENCE SCHQA_ORCL_DESARCHIVE_AUTEN.SEQ_DETALLE_USUARIO START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER SCHQA_ORCL_DESARCHIVE_AUTEN.TRG_DETALLE_USUARIO BEFORE
    INSERT ON SCHQA_ORCL_DESARCHIVE_AUTEN.DETALLE_USUARIO
    FOR EACH ROW
    WHEN ( NEW.ID_DETALLE_USUARIO IS NULL )
BEGIN
    :NEW.ID_DETALLE_USUARIO := SCHQA_ORCL_DESARCHIVE_AUTEN.SEQ_DETALLE_USUARIO.NEXTVAL;
END;

