/*
-------------------------------------------------------------------------------------------------------------------------------
-- OBJETIVO                  : Script de insercion de las tablas del Modelo
                               
-- PARÁMETROS DE ENTRADA     : N/A
-- PARÁMETROS DE SALIDA      : NA   
-- OBJETOS QUE LO REFERENCIAN: NA
-- LIDER TÉCNICO             :              
-- FECHAHORA                 : 2021/10/14
-- REALIZADO POR             : INFORMATICA & TECNOLOGIA (GEDV - JAPC)
--	                           Este componente fue realizado bajo la metodología de desarrollo de Informática & Tecnología 
--                             y se encuentra Protegido por las leyes de derechos de autor.
-- FECHAHORA MODIFICACIÓN    : 
-- LIDER MODIFICACIÓN        : 
-- REALIZADO POR             : 
-- OBJETIVO MODIFICACIÓN     : 
-----------------------------------------------------------------------------------------------------------------------------
*/

INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10002,'CIVIL CIRCUITO',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10003,'CIVIL MUNICIPAL',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10004,'CIVIL MUNICIPAL DESCONGESTIÓN',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10005,'CIVIL MUNICIPAL EJECUCIÓN',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10006,'CIVIL MUNICIPAL PEQUEÑAS CAUSAS',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10007,'EJECUCIÓN CIVIL CIRCUITO',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10008,'FAMILIA',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10009,'FAMILIA EJECUCIÓN',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10010,'LABORAL',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10011,'LABORAL PEQUEÑAS CAUSAS',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10012,'PENAL MUNICIPAL DE CONTROL DE GARANTÍAS TUTELAS',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10013,'PENAL MUNICIPAL DE CONOCIMIENTO TUTELAS',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10014,'PENAL CIRCUITO DE CONOCIMIENTO TUTELAS',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10015,'PENAL MUNICIPAL LEY 600',1);
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCHQA_ORCL_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10016,'PENAL CIRCUITO LEY 600',1);
COMMIT;

INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'1111','BODEGAUNO','125325','DIR PRUEBA','1','0');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'4','BOD SER','8521','DERFV','1','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'6','DOSWEB','865232','YUJJNN','51','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'10','PRUEBA','855555','CALLE LA VIRGEN','1097','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'7','BODEGATEST','TEST','DIR TEST','1','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'8','PORTAL','478521','PORTAL','138','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'9','PORTALDOS','88888','PORTAL','382','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'11','BOEDAGA DEL MU','85221','CUMDLIS C','51','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'12','ULTIMA','52132','DFKJFDHSD','51','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'18','DSADSADAS','3343244','43243243242','51','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'2121','APENAS','1252525','DIRECCION O ','70','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'19','PABLO PRUEBA','55555555','DIRECION','151','0');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'20','NUEVO NUW','77777','ETYDID','138','0');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'3','BODEGA TRES','586712','CALLE CIEGA','1','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'13','BODEGA DECIMA','521223','CALLE DECIMA','51','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'2','BODEGA DOS','8521475','DIECCION PRUEBA DOS','1','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'14','FDSFDSFDSFDSD','FDDFDFDD','FDFDFSFDS','51','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'5','WEBJJJ','DSADA','SDSADA','51','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'15','YHTNTNTN','JJJJJJJ','JJJJJJ','51','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'16','PRUEBA ANDREA','52326','CALLE SIN','152','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ID_MUNICIPIO,ES_ACTIVO) VALUES (SCHQA_ORCL_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'17','OTRA PREU','00000000','FIRIEOEK','358','1');
COMMIT;

INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('6','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('6','2');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('8','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('8','2');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('13','2');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('13','3');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('11','2');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('11','3');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('12','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('12','2');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('12','3');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('1','2');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('1','1');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('7','2');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('7','3');
COMMIT;

INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.USUARIO_POR_BODEGA (ID_USUARIO,ID_BODEGA) VALUES ('1','13');
INSERT INTO SCHQA_ORCL_DESARCHIVE_CORE.USUARIO_POR_BODEGA (ID_USUARIO,ID_BODEGA) VALUES ('4','12');
COMMIT;