/*
-------------------------------------------------------------------------------------------------------------------------------
-- OBJETIVO                  : Script de insercion de las tablas del Modelo
                               
-- PARÁMETROS DE ENTRADA     : N/A
-- PARÁMETROS DE SALIDA      : NA   
-- OBJETOS QUE LO REFERENCIAN: NA
-- LIDER TÉCNICO             :              
-- FECHAHORA                 : 2021/11/24
-- REALIZADO POR             : INFORMATICA & TECNOLOGIA (GEDV - JAPC)
--	                           Este componente fue realizado bajo la metodología de desarrollo de Informática & Tecnología 
--                             y se encuentra Protegido por las leyes de derechos de autor.
-- FECHAHORA MODIFICACIÓN    : 
-- LIDER MODIFICACIÓN        : 
-- REALIZADO POR             : 
-- OBJETIVO MODIFICACIÓN     : 
-----------------------------------------------------------------------------------------------------------------------------
*/
INSERT INTO SCH_ORCL_DESARCHIVE_SWEB.ESTADO_SOLICITUD(ID_ESTADO_SOLICITUD,NOMBRE,CODIGO,ES_ACTIVO)VALUES(SCH_ORCL_DESARCHIVE_SWEB.SEQ_ESTADO_SOLICITUD.NEXTVAL,'RADICADA',1,1);
INSERT INTO SCH_ORCL_DESARCHIVE_SWEB.ESTADO_SOLICITUD(ID_ESTADO_SOLICITUD,NOMBRE,CODIGO,ES_ACTIVO)VALUES(SCH_ORCL_DESARCHIVE_SWEB.SEQ_ESTADO_SOLICITUD.NEXTVAL,'SIN PAGO ONLINE',2,1);
INSERT INTO SCH_ORCL_DESARCHIVE_SWEB.ESTADO_SOLICITUD(ID_ESTADO_SOLICITUD,NOMBRE,CODIGO,ES_ACTIVO)VALUES(SCH_ORCL_DESARCHIVE_SWEB.SEQ_ESTADO_SOLICITUD.NEXTVAL,'CON PAGO ONLINE',3,1);
INSERT INTO SCH_ORCL_DESARCHIVE_SWEB.ESTADO_SOLICITUD(ID_ESTADO_SOLICITUD,NOMBRE,CODIGO,ES_ACTIVO)VALUES(SCH_ORCL_DESARCHIVE_SWEB.SEQ_ESTADO_SOLICITUD.NEXTVAL,'SIN PAGO FISICO',4,1);
INSERT INTO SCH_ORCL_DESARCHIVE_SWEB.ESTADO_SOLICITUD(ID_ESTADO_SOLICITUD,NOMBRE,CODIGO,ES_ACTIVO)VALUES(SCH_ORCL_DESARCHIVE_SWEB.SEQ_ESTADO_SOLICITUD.NEXTVAL,'CON PAGO FISICO',5,2);
INSERT INTO SCH_ORCL_DESARCHIVE_SWEB.ESTADO_SOLICITUD(ID_ESTADO_SOLICITUD,NOMBRE,CODIGO,ES_ACTIVO)VALUES(SCH_ORCL_DESARCHIVE_SWEB.SEQ_ESTADO_SOLICITUD.NEXTVAL,'PENDIENTE',6,2);
INSERT INTO SCH_ORCL_DESARCHIVE_SWEB.ESTADO_SOLICITUD(ID_ESTADO_SOLICITUD,NOMBRE,CODIGO,ES_ACTIVO)VALUES(SCH_ORCL_DESARCHIVE_SWEB.SEQ_ESTADO_SOLICITUD.NEXTVAL,'POR ENTREGAR',7,2);
INSERT INTO SCH_ORCL_DESARCHIVE_SWEB.ESTADO_SOLICITUD(ID_ESTADO_SOLICITUD,NOMBRE,CODIGO,ES_ACTIVO)VALUES(SCH_ORCL_DESARCHIVE_SWEB.SEQ_ESTADO_SOLICITUD.NEXTVAL,'ENTREGADA',8,2);
COMMIT;
