/*
-------------------------------------------------------------------------------------------------------------------------------
-- OBJETIVO                  : CREACION DEL MODELO RELACIONAL BD DESARCHIVE SITIO WEB MODULO DESARCHIVE.
-- PARÁMETROS DE ENTRADA     : LA EJECUCIÓN DEL SCRIPT SOLICITA LOS SIGUIENTES PARAMETROS
								SERVICIO        : ORCL_DESARCHIVE_CORE_PRE
								SIZE_TABLESPACE : DEVOPS -> 10
								                  19C    -> 1000
												  21C    -> 1000
-- PARÁMETROS DE SALIDA      : NA   
-- OBJETOS QUE LO REFERENCIAN: NA
-- LIDER TÉCNICO             : GABRIEL EDUARDO DUARTE             
-- FECHAHORA                 : 2021/11/30
-- REALIZADO POR             : INFORMATICA & TECNOLOGIA (GEDV - JAPC)
--	                           ESTE COMPONENTE FUE REALIZADO BAJO LA METODOLOGÍA DE DESARROLLO DE INFORMÁTICA & TECNOLOGÍA 
--                             Y SE ENCUENTRA PROTEGIDO POR LAS LEYES DE DERECHOS DE AUTOR.
-- FECHAHORA MODIFICACIÓN    : 
-- LIDER MODIFICACIÓN        : 
-- REALIZADO POR             : 
-- OBJETIVO MODIFICACIÓN     : 
--                             
-----------------------------------------------------------------------------------------------------------------------------
*/
DECLARE
   V_CREASERVICIO   VARCHAR2(4000);
   V_INICIASERVICIO VARCHAR2(4000);
   V_SERVICIO       VARCHAR2(500);
   V_SIZE_TBL       NUMBER;
   V_CREATABLESDATA VARCHAR2(4000);
   V_CREATABLESIDX  VARCHAR2(4000);
   V_RUTA           VARCHAR2(500);
   V_RUTA_DATA      VARCHAR2(500);
   V_RUTA_IDX       VARCHAR2(500);
   V_CREA_USUARIO   VARCHAR2(500);
   V_USUARIO        VARCHAR2(500);
   V_CREA_ROL       VARCHAR2(500);   
   
BEGIN
    DELETE FROM AUDITORIA_OBJETOS;COMMIT;
	PROC_AUDITA_OBJETOS('DESARCHIVE SITIO WEB','ORCL_DESARCHIVE_CORE_PRE','CREACION BD',NULL,NULL);
    V_SERVICIO := '&SERVICIO';
	V_SIZE_TBL := '&SIZE_TABLESPACE';
    --CREANDO SERVICIO
    V_CREASERVICIO := 'BEGIN
                          DBMS_SERVICE.CREATE_SERVICE(
                            SERVICE_NAME => :SERVICIO,
                            NETWORK_NAME => :SERVICIO);
                        END;';
    EXECUTE IMMEDIATE V_CREASERVICIO USING V_SERVICIO;                    
    PROC_AUDITA_OBJETOS(NULL,NULL,'CREA SERVICIO '||V_SERVICIO||' OK.',NULL,NULL);

    --INICIANDO SERVICIO
    V_INICIASERVICIO := ' BEGIN
                           DBMS_SERVICE.START_SERVICE(SERVICE_NAME => :SERVICIO);
                        END;';
    EXECUTE IMMEDIATE V_INICIASERVICIO USING V_SERVICIO;
    PROC_AUDITA_OBJETOS(NULL,NULL,'INICIA SERVICIO '||V_SERVICIO||' OK.',NULL,NULL);
    
    EXECUTE IMMEDIATE 'CREATE ROLE ROL_DESARCHIVE_CORE_PRE';
    PROC_AUDITA_OBJETOS(NULL,NULL,'CREA ROL OK.',NULL,NULL);
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER,CREATE PROCEDURE TO ROL_DESARCHIVE_CORE_PRE';
    PROC_AUDITA_OBJETOS(NULL,NULL,'OTORGA PERMISOS OK.',NULL,NULL);
    
    ---OBTENIENDO RUTA DE INSTALACION DEL MOTOR
    SELECT SUBSTR(FILE_NAME,1,INSTR(FILE_NAME,'\',-1))
    INTO   V_RUTA
    FROM   DBA_DATA_FILES
    WHERE  ROWNUM = 1;

    ---CREANDO TABLESPACEDATA
    V_RUTA_DATA      := V_RUTA||V_SERVICIO||'_DATA.DBF';
    V_CREATABLESDATA := 'CREATE TABLESPACE '||V_SERVICIO||'_DATA DATAFILE '''||V_RUTA_DATA||''' SIZE '||V_SIZE_TBL||'M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED';
    EXECUTE IMMEDIATE V_CREATABLESDATA;
    PROC_AUDITA_OBJETOS(NULL,NULL,'CREA TABLESPACE DATA '||V_RUTA_DATA||' OK...',NULL,NULL);

    ---CREANDO TABLESPACE IDX
    V_RUTA_IDX      := V_RUTA||V_SERVICIO||'_IDX.DBF';
    V_CREATABLESIDX := 'CREATE TABLESPACE '||V_SERVICIO||'_IDX  DATAFILE '''||V_RUTA_IDX||''' SIZE '||V_SIZE_TBL||'M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED';
    EXECUTE IMMEDIATE V_CREATABLESIDX;
    PROC_AUDITA_OBJETOS(NULL,NULL,'CREA TABLESPACE IDX '||V_RUTA_IDX||' OK...',NULL,NULL);

    ---CREANDO USUARIO
    V_USUARIO := 'SCH_'||V_SERVICIO;
    V_CREA_USUARIO := '
                    CREATE USER '||V_USUARIO||' IDENTIFIED BY '||V_USUARIO||'
                    DEFAULT TABLESPACE '||V_SERVICIO||'_DATA
                    TEMPORARY TABLESPACE TEMP
                    QUOTA UNLIMITED ON '||V_SERVICIO||'_DATA';
    EXECUTE IMMEDIATE V_CREA_USUARIO;   
    PROC_AUDITA_OBJETOS(NULL,NULL,'CREA USUARIO '||V_USUARIO||' OK...',NULL,NULL);

    ---OTORGANDO PERMISOS AL USUARIO
    EXECUTE IMMEDIATE 'GRANT ROL_DESARCHIVE_CORE_PRE TO '||V_USUARIO;
    PROC_AUDITA_OBJETOS(NULL,NULL,'OTORTANDO PERMISOS ROL, OK...',NULL,NULL);
    PROC_AUDITA_OBJETOS(NULL,NULL,'INICIA CREACION OBJETOS BD ....',NULL,NULL);
EXCEPTION
  WHEN OTHERS THEN
    PROC_AUDITA_OBJETOS(NULL,NULL,'ERROR DURANTE INSTALACION BD',SQLCODE,SQLERRM);
END;
/

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.ANIO (
    ID_ANIO   NUMBER(38) NOT NULL,
    CODIGO    NVARCHAR2(2000) NOT NULL,
    ES_ACTIVO NUMBER(1) NOT NULL
);

CREATE UNIQUE INDEX SCH_ORCL_DESARCHIVE_CORE_PRE.IDX_CODIGO_ANIO ON
    SCH_ORCL_DESARCHIVE_CORE_PRE.ANIO (
        CODIGO
    ASC );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.ANIO ADD CONSTRAINT PK_ANI PRIMARY KEY ( ID_ANIO );

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.BODEGA (
    ID_BODEGA      NUMBER(38) NOT NULL,
    IDENTIFICACION NVARCHAR2(1000) NOT NULL,
    NOMBRE         NVARCHAR2(1000) NOT NULL,
    TELEFONO       NVARCHAR2(500) NOT NULL,
    DIRECCION      NVARCHAR2(1000) NOT NULL,
    ES_ACTIVO      NUMBER(1) NOT NULL,
    ID_MUNICIPIO   NUMBER(38) NOT NULL
);

CREATE UNIQUE INDEX SCH_ORCL_DESARCHIVE_CORE_PRE.IDX_IDENTIFICACION ON
    SCH_ORCL_DESARCHIVE_CORE_PRE.BODEGA (
        IDENTIFICACION
    ASC );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.BODEGA ADD CONSTRAINT PK_BDG PRIMARY KEY ( ID_BODEGA );

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.ESP_X_TIPO_PROCESO (
    ID_TIPO_PROCESO      NUMBER(38) NOT NULL,
    ID_ESPECIALIDAD      NUMBER(38) NOT NULL,
    REQUIERE_PAGO        NUMBER(1),
    ES_VISIBLE_SITIO_WEB NUMBER(1)
);

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.ESP_X_TIPO_PROCESO ADD CONSTRAINT PK_EXT PRIMARY KEY ( ID_TIPO_PROCESO,
                                                                                                ID_ESPECIALIDAD );

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.ESPECIALIDAD (
    ID_ESPECIALIDAD NUMBER(38) NOT NULL,
    CODIGO          NVARCHAR2(2000) NOT NULL,
    NOMBRE          NVARCHAR2(30) NOT NULL,
    ES_ACTIVO       NUMBER(1) NOT NULL,
    ID_JURISDICCION NUMBER(38) NOT NULL
);

CREATE UNIQUE INDEX SCH_ORCL_DESARCHIVE_CORE_PRE.IDX_CODIGO_ESPECIALIDAD ON
    SCH_ORCL_DESARCHIVE_CORE_PRE.ESPECIALIDAD (
        CODIGO
    ASC );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.ESPECIALIDAD ADD CONSTRAINT PK_ESP PRIMARY KEY ( ID_ESPECIALIDAD );

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.HISTORICO_TARIFA (
    ID_HISTORICO_TARIFA NUMBER(38) NOT NULL,
    NOMBRE              NVARCHAR2(2000),
    CODIGO              NVARCHAR2(1000),
    VALOR               NUMBER(19, 4),
    FECHA_ACTUALIZACION DATE,
    ID_TARIFA           NUMBER(38) NOT NULL
);

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.HISTORICO_TARIFA ADD CONSTRAINT PK_HTF PRIMARY KEY ( ID_HISTORICO_TARIFA );

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.JURISDICCION (
    ID_JURISDICCION NUMBER(38) NOT NULL,
    CODIGO          NVARCHAR2(2000) NOT NULL,
    NOMBRE          NVARCHAR2(1000) NOT NULL,
    ES_ACTIVO       NUMBER(1) NOT NULL
);

CREATE UNIQUE INDEX SCH_ORCL_DESARCHIVE_CORE_PRE.IDX_JDC_CODIGO ON
    SCH_ORCL_DESARCHIVE_CORE_PRE.JURISDICCION (
        CODIGO
    ASC );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.JURISDICCION ADD CONSTRAINT PK_JDC PRIMARY KEY ( ID_JURISDICCION );

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.JURISDICCION_POR_BODEGA (
    ID_BODEGA       NUMBER(38) NOT NULL,
    ID_JURISDICCION NUMBER(38) NOT NULL
);

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.JURISDICCION_POR_BODEGA ADD CONSTRAINT PK_JXB PRIMARY KEY ( ID_BODEGA,
                                                                                                     ID_JURISDICCION );

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.JUZGADO (
    ID_JUZGADO       NUMBER(38) NOT NULL,
    CODIGO           NVARCHAR2(2000) NOT NULL,
    NOMBRE           NVARCHAR2(30) NOT NULL,
    ES_ACTIVO        NUMBER(1) NOT NULL,
    CODIGO_MUNICIPIO NVARCHAR2(2000),
    ID_ESPECIALIDAD  NUMBER(38) NOT NULL
);

CREATE UNIQUE INDEX SCH_ORCL_DESARCHIVE_CORE_PRE.IDX_CODIGO_JUZGADO ON
    SCH_ORCL_DESARCHIVE_CORE_PRE.JUZGADO (
        CODIGO
    ASC );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.JUZGADO ADD CONSTRAINT PK_JUZ PRIMARY KEY ( ID_JUZGADO );

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.TARIFA (
    ID_TARIFA           NUMBER(38) NOT NULL,
    NOMBRE              NVARCHAR2(2000) NOT NULL,
    CODIGO              NVARCHAR2(1000) NOT NULL,
    VALOR               NUMBER(19, 4) NOT NULL,
    FECHA_ACTUALIZACION DATE NOT NULL
);

CREATE UNIQUE INDEX SCH_ORCL_DESARCHIVE_CORE_PRE.IDX_TARIFA ON
    SCH_ORCL_DESARCHIVE_CORE_PRE.TARIFA (
        CODIGO
    ASC );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.TARIFA ADD CONSTRAINT PK_TRA PRIMARY KEY ( ID_TARIFA );

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.TIPO_PROCESO (
    ID_TIPO_PROCESO NUMBER(38) NOT NULL,
    CODIGO          NVARCHAR2(2000) NOT NULL,
    NOMBRE          NVARCHAR2(30) NOT NULL,
    ES_ACTIVO       NUMBER(1) NOT NULL
);

CREATE UNIQUE INDEX SCH_ORCL_DESARCHIVE_CORE_PRE.IDX_CODIGO_TIPO_PROC ON
    SCH_ORCL_DESARCHIVE_CORE_PRE.TIPO_PROCESO (
        CODIGO
    ASC );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.TIPO_PROCESO ADD CONSTRAINT PK_TPP PRIMARY KEY ( ID_TIPO_PROCESO );

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.TIPO_SUJETO_PROCESAL (
    ID_TIPO_SUJETO_PROCESAL NUMBER(38) NOT NULL,
    CODIGO                  NVARCHAR2(1000) NOT NULL,
    NOMBRE                  NVARCHAR2(1000) NOT NULL,
    ES_ACTIVO               NUMBER(1) NOT NULL
);

CREATE UNIQUE INDEX SCH_ORCL_DESARCHIVE_CORE_PRE.IDX_CODIGO_TP_SPROCESAL ON
    SCH_ORCL_DESARCHIVE_CORE_PRE.TIPO_SUJETO_PROCESAL (
        CODIGO
    ASC );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.TIPO_SUJETO_PROCESAL ADD CONSTRAINT TIPO_SUJETO_PROCESAL_PK PRIMARY KEY ( ID_TIPO_SUJETO_PROCESAL );

CREATE TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.USUARIO_POR_BODEGA (
    ID_BODEGA                  NUMBER(38) NOT NULL,
    CODIGO_TIPO_IDENTIFICACION NVARCHAR2(1000) NOT NULL,
    NUMERO_IDENTIFICACION      NVARCHAR2(1000) NOT NULL
);

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.USUARIO_POR_BODEGA
    ADD CONSTRAINT PK_USU_BDG PRIMARY KEY ( ID_BODEGA,
                                            CODIGO_TIPO_IDENTIFICACION,
                                            NUMERO_IDENTIFICACION );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.JURISDICCION_POR_BODEGA
    ADD CONSTRAINT FK_BDG_JXB FOREIGN KEY ( ID_BODEGA )
        REFERENCES SCH_ORCL_DESARCHIVE_CORE_PRE.BODEGA ( ID_BODEGA );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.ESP_X_TIPO_PROCESO
    ADD CONSTRAINT FK_ESP_EXT FOREIGN KEY ( ID_ESPECIALIDAD )
        REFERENCES SCH_ORCL_DESARCHIVE_CORE_PRE.ESPECIALIDAD ( ID_ESPECIALIDAD );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.JUZGADO
    ADD CONSTRAINT FK_ESP_JUZ FOREIGN KEY ( ID_ESPECIALIDAD )
        REFERENCES SCH_ORCL_DESARCHIVE_CORE_PRE.ESPECIALIDAD ( ID_ESPECIALIDAD );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.ESPECIALIDAD
    ADD CONSTRAINT FK_JDC_ESP FOREIGN KEY ( ID_JURISDICCION )
        REFERENCES SCH_ORCL_DESARCHIVE_CORE_PRE.JURISDICCION ( ID_JURISDICCION );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.JURISDICCION_POR_BODEGA
    ADD CONSTRAINT FK_JDC_JXB FOREIGN KEY ( ID_JURISDICCION )
        REFERENCES SCH_ORCL_DESARCHIVE_CORE_PRE.JURISDICCION ( ID_JURISDICCION );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.ESP_X_TIPO_PROCESO
    ADD CONSTRAINT FK_TPP_EXT FOREIGN KEY ( ID_TIPO_PROCESO )
        REFERENCES SCH_ORCL_DESARCHIVE_CORE_PRE.TIPO_PROCESO ( ID_TIPO_PROCESO );

ALTER TABLE SCH_ORCL_DESARCHIVE_CORE_PRE.HISTORICO_TARIFA
    ADD CONSTRAINT FK_TRA_HTF FOREIGN KEY ( ID_TARIFA )
        REFERENCES SCH_ORCL_DESARCHIVE_CORE_PRE.TARIFA ( ID_TARIFA );

CREATE SEQUENCE SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_ANIO START WITH 1 CACHE 100 ORDER;

CREATE OR REPLACE TRIGGER SCH_ORCL_DESARCHIVE_CORE_PRE.TRG_ANIO BEFORE
    INSERT ON SCH_ORCL_DESARCHIVE_CORE_PRE.ANIO
    FOR EACH ROW
    WHEN ( NEW.ID_ANIO IS NULL )
BEGIN
    :NEW.ID_ANIO := SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_ANIO.NEXTVAL;
END;
/

CREATE SEQUENCE SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_BODEGA START WITH 1 CACHE 100 ORDER;

CREATE OR REPLACE TRIGGER SCH_ORCL_DESARCHIVE_CORE_PRE.TRG_BODEGA BEFORE
    INSERT ON SCH_ORCL_DESARCHIVE_CORE_PRE.BODEGA
    FOR EACH ROW
    WHEN ( NEW.ID_BODEGA IS NULL )
BEGIN
    :NEW.ID_BODEGA := SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_BODEGA.NEXTVAL;
END;
/

CREATE SEQUENCE SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_ESPECIALIDAD START WITH 1 CACHE 100 ORDER;

CREATE OR REPLACE TRIGGER SCH_ORCL_DESARCHIVE_CORE_PRE.TRG_ESPECIALIDAD BEFORE
    INSERT ON SCH_ORCL_DESARCHIVE_CORE_PRE.ESPECIALIDAD
    FOR EACH ROW
    WHEN ( NEW.ID_ESPECIALIDAD IS NULL )
BEGIN
    :NEW.ID_ESPECIALIDAD := SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_ESPECIALIDAD.NEXTVAL;
END;
/

CREATE SEQUENCE SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_HISTORICO_TARIFA START WITH 1 CACHE 20 ORDER;

CREATE OR REPLACE TRIGGER SCH_ORCL_DESARCHIVE_CORE_PRE.TRG_HISTORICO_TARIFA BEFORE
    INSERT ON SCH_ORCL_DESARCHIVE_CORE_PRE.HISTORICO_TARIFA
    FOR EACH ROW
    WHEN ( NEW.ID_HISTORICO_TARIFA IS NULL )
BEGIN
    :NEW.ID_HISTORICO_TARIFA := SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_HISTORICO_TARIFA.NEXTVAL;
END;
/

CREATE SEQUENCE SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_JURISDICCION START WITH 1 CACHE 100 ORDER;

CREATE OR REPLACE TRIGGER SCH_ORCL_DESARCHIVE_CORE_PRE.TRG_JURISDICCION BEFORE
    INSERT ON SCH_ORCL_DESARCHIVE_CORE_PRE.JURISDICCION
    FOR EACH ROW
    WHEN ( NEW.ID_JURISDICCION IS NULL )
BEGIN
    :NEW.ID_JURISDICCION := SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_JURISDICCION.NEXTVAL;
END;
/

CREATE SEQUENCE SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_JUZGADO START WITH 1 CACHE 100 ORDER;

CREATE OR REPLACE TRIGGER SCH_ORCL_DESARCHIVE_CORE_PRE.TRG_JUZGADO BEFORE
    INSERT ON SCH_ORCL_DESARCHIVE_CORE_PRE.JUZGADO
    FOR EACH ROW
    WHEN ( NEW.ID_JUZGADO IS NULL )
BEGIN
    :NEW.ID_JUZGADO := SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_JUZGADO.NEXTVAL;
END;
/

CREATE SEQUENCE SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_TARIFA START WITH 1 CACHE 20 ORDER;

CREATE OR REPLACE TRIGGER SCH_ORCL_DESARCHIVE_CORE_PRE.TRG__TARIFA BEFORE
    INSERT ON SCH_ORCL_DESARCHIVE_CORE_PRE.TARIFA
    FOR EACH ROW
    WHEN ( NEW.ID_TARIFA IS NULL )
BEGIN
    :NEW.ID_TARIFA := SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_TARIFA.NEXTVAL;
END;
/

CREATE SEQUENCE SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_TIPO_PROCESO START WITH 1 CACHE 100 ORDER;

CREATE OR REPLACE TRIGGER SCH_ORCL_DESARCHIVE_CORE_PRE.TRG_TIPO_PROCESO BEFORE
    INSERT ON SCH_ORCL_DESARCHIVE_CORE_PRE.TIPO_PROCESO
    FOR EACH ROW
    WHEN ( NEW.ID_TIPO_PROCESO IS NULL )
BEGIN
    :NEW.ID_TIPO_PROCESO := SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_TIPO_PROCESO.NEXTVAL;
END;
/

CREATE SEQUENCE SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_TIPO_SUJETO_PROCESAL START WITH 1 CACHE 100 ORDER;

CREATE OR REPLACE TRIGGER SCH_ORCL_DESARCHIVE_CORE_PRE.TRG_TIPO_SUJETO_PROCESAL BEFORE
    INSERT ON SCH_ORCL_DESARCHIVE_CORE_PRE.TIPO_SUJETO_PROCESAL
    FOR EACH ROW
    WHEN ( NEW.ID_TIPO_SUJETO_PROCESAL IS NULL )
BEGIN
    :NEW.ID_TIPO_SUJETO_PROCESAL := SCH_ORCL_DESARCHIVE_CORE_PRE.SEQ_TIPO_SUJETO_PROCESAL.NEXTVAL;
END;
/

--- GENERACION DE PERMISOS 
DECLARE
  V_ROL  VARCHAR2(4000);
  CURSOR C_PERMISOS
  IS 
    SELECT 'GRANT SELECT, INSERT, UPDATE, DELETE ON SCH_ORCL_DESARCHIVE_CORE_PRE.'||TABLE_NAME||' TO ' AS SENTENCIA
    FROM   USER_TABLES;
  R_PER C_PERMISOS%ROWTYPE;
BEGIN
  PROC_AUDITA_OBJETOS(NULL,NULL,'FINALIZA CREACION OBJETOS OK....',NULL,NULL);
  PROC_AUDITA_OBJETOS(NULL,NULL,'INICIA ASIGNACION PERMISOS OBJETOS....',NULL,NULL);
  V_ROL := 'ROL_DESARCHIVE_CORE_PRE';
  OPEN C_PERMISOS;
  LOOP
    FETCH C_PERMISOS INTO R_PER;
    EXIT WHEN C_PERMISOS%NOTFOUND;
      EXECUTE IMMEDIATE R_PER.SENTENCIA||V_ROL;
  END LOOP;
  CLOSE C_PERMISOS;
  PROC_AUDITA_OBJETOS(NULL,NULL,'FINALIZA ASIGNACION PERMISOS OBJETOS OK....',NULL,NULL);
EXCEPTION
  WHEN OTHERS THEN
    IF C_PERMISOS%ISOPEN THEN CLOSE C_PERMISOS; END IF;
	PROC_AUDITA_OBJETOS(NULL,NULL,'ERROR GENERANDO PERMISOS....',SQLCODE,SQLERRM);
END;
/
DECLARE
  V_TEXTO VARCHAR2(4000);
  V_IDX   VARCHAR2(4000):= 'ORCL_DESARCHIVE_CORE_PRE_IDX';
  V_OW    VARCHAR2(4000):= 'SCH_ORCL_DESARCHIVE_CORE_PRE';
  CURSOR C_INDEX(P_TBL_IDX VARCHAR2,
                 P_TBL_OW  VARCHAR2)
  IS 
    SELECT ('ALTER INDEX '||OWNER||'.'||INDEX_NAME||' REBUILD TABLESPACE '||P_TBL_IDX)AS SENTENCIA
    FROM ALL_INDEXES WHERE OWNER = V_OW; 
  R_INDEX C_INDEX%ROWTYPE;
BEGIN
  PROC_AUDITA_OBJETOS(NULL,NULL,'INICIA ASIGNACION INDICES OBJETOS A TABLESPACE IDX....',NULL,NULL);
  OPEN C_INDEX(V_IDX,V_OW);
  LOOP
  FETCH C_INDEX INTO R_INDEX;
  EXIT WHEN C_INDEX%NOTFOUND;
    EXECUTE IMMEDIATE R_INDEX.SENTENCIA;
  END LOOP;
  CLOSE C_INDEX;
  EXECUTE IMMEDIATE 'ALTER USER '||V_OW||' QUOTA 1000M ON '||V_IDX||'';  -- ASIGNA LA CUOTA AL TABLESPACE DE INDICE
  PROC_AUDITA_OBJETOS(NULL,NULL,'FINALIZA ASIGNACION INDICES OBJETOS A TABLESPACE IDX OK....',NULL,NULL);
  PROC_AUDITA_OBJETOS('DESARCHIVE SITIO WEB','ORCL_DESARCHIVE_CORE_PRE','FINALIZACION CREACION BD',NULL,NULL);
EXCEPTION
  WHEN OTHERS THEN
    IF C_INDEX%ISOPEN THEN CLOSE C_INDEX; END IF;
    PROC_AUDITA_OBJETOS(NULL,NULL,'ERROR ASIGNANDO OBJ A TABLESPACES IDX....',SQLCODE,SQLERRM);
END;