/*
-------------------------------------------------------------------------------------------------------------------------------
-- OBJETIVO                  : Script de insercion de las tablas del Modelo
                               
-- PARÁMETROS DE ENTRADA     : N/A
-- PARÁMETROS DE SALIDA      : NA   
-- OBJETOS QUE LO REFERENCIAN: NA
-- LIDER TÉCNICO             :              
-- FECHAHORA                 : 2021/10/14
-- REALIZADO POR             : INFORMATICA & TECNOLOGIA (GEDV - JAPC)
--	                           Este componente fue realizado bajo la metodología de desarrollo de Informática & Tecnología 
--                             y se encuentra Protegido por las leyes de derechos de autor.
-- FECHAHORA MODIFICACIÓN    : 
-- LIDER MODIFICACIÓN        : 
-- REALIZADO POR             : 
-- OBJETIVO MODIFICACIÓN     : 
-----------------------------------------------------------------------------------------------------------------------------
*/

INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,1,'CIVIL CIRCUITO',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,2,'CIVIL MUNICIPAL',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,3,'CIVIL MUNICIPAL DESCONGESTIÓN',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,4,'CIVIL MUNICIPAL EJECUCIÓN',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,5,'CIVIL MUNICIPAL PEQUEÑAS CAUSAS',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,6,'EJECUCIÓN CIVIL CIRCUITO',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,7,'FAMILIA',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,8,'FAMILIA EJECUCIÓN',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,9,'LABORAL',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,10,'LABORAL PEQUEÑAS CAUSAS',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,11,'PENAL MUNICIPAL DE CONTROL DE GARANTÍAS TUTELAS',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,12,'PENAL MUNICIPAL DE CONOCIMIENTO TUTELAS',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,13,'PENAL CIRCUITO DE CONOCIMIENTO TUTELAS',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,14,'PENAL MUNICIPAL LEY 600',1);
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION(ID_JURISDICCION,CODIGO,NOMBRE,ES_ACTIVO)VALUES(SCH_ORCLQA_DESARCHIVE_CORE.SEQ_JURISDICCION.NEXTVAL,15,'PENAL CIRCUITO LEY 600',1);
COMMIT;

INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'1111','BODEGAUNO','125325','DIR PRUEBA','0','1');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'4','BOD SER','8521','DERFV','1','1');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'6','DOSWEB','865232','YUJJNN','1','51');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'10','PRUEBA','855555','CALLE LA VIRGEN','1','1097');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'7','BODEGATEST','TEST','DIR TEST','1','1');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'8','PORTAL','478521','PORTAL','1','138');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'9','PORTALDOS','88888','PORTAL','1','382');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'11','BOEDAGA DEL MU','85221','CUMDLIS C','1','51');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'12','ULTIMA','52132','DFKJFDHSD','1','51');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'18','DSADSADAS','3343244','43243243242','1','51');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'2121','APENAS','1252525','DIRECCION O ','1','70');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'19','PABLO PRUEBA','55555555','DIRECION','0','151');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'20','NUEVO NUW','77777','ETYDID','0','138');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'3','BODEGA TRES','586712','CALLE CIEGA','1','1');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'13','BODEGA DECIMA','521223','CALLE DECIMA','1','51');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'2','BODEGA DOS','8521475','DIECCION PRUEBA DOS','1','1');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'14','FDSFDSFDSFDSD','FDDFDFDD','FDFDFSFDS','1','51');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'5','WEBJJJ','DSADA','SDSADA','1','51');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'15','YHTNTNTN','JJJJJJJ','JJJJJJ','1','51');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'16','PRUEBA ANDREA','52326','CALLE SIN','1','152');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.BODEGA (ID_BODEGA,IDENTIFICACION,NOMBRE,TELEFONO,DIRECCION,ES_ACTIVO,ID_MUNICIPIO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_BODEGA.NEXTVAL,'17','OTRA PREU','00000000','FIRIEOEK','1','358');
COMMIT;


INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('6','1');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('6','2');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('8','1');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('8','2');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('13','2');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('13','3');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('11','2');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('11','3');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('12','1');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('12','2');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('12','3');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('1','2');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('1','1');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('7','2');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.JURISDICCION_POR_BODEGA (ID_BODEGA,ID_JURISDICCION) VALUES ('7','3');
COMMIT;


INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.USUARIO_POR_BODEGA (ID_BODEGA,CODIGO_TIPO_IDENTIFICACION,NUMERO_IDENTIFICACION) VALUES ('13','CC','10204857576');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.USUARIO_POR_BODEGA (ID_BODEGA,CODIGO_TIPO_IDENTIFICACION,NUMERO_IDENTIFICACION) VALUES ('12','CE','80040257');
COMMIT;


INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.TIPO_PROCESO(ID_TIPO_PROCESO,CODIGO,NOMBRE,ES_ACTIVO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_TIPO_PROCESO.NEXTVAL,'T001','TUTELA','1');
INSERT INTO SCH_ORCLQA_DESARCHIVE_CORE.TIPO_PROCESO(ID_TIPO_PROCESO,CODIGO,NOMBRE,ES_ACTIVO) VALUES (SCH_ORCLQA_DESARCHIVE_CORE.SEQ_TIPO_PROCESO.NEXTVAL,'T002','PROCESO','1');
COMMIT;